language: java
script:
  - mvn clean test jacoco:report package sonar:sonar 
jdk:
  - oraclejdk8
after_success:
  - mvn clean cobertura:cobertura coveralls:report
sudo: false
addons:
  sonarcloud:
    organization: "leonardxfce-github"
    token:
      secure: $SONAR_TOKEN
env:
    - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
 