os: osx
language: java
script:
  - mvn test -B
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
after_success:
  - mvn cobertura:cobertura coveralls:report  
jdk:
  - oraclejdk8
sudo: false
addons:
  sonarcloud:
    organization: "9024-XP"
    token:
      secure: $SONAR_TOKEN
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
  