os: osx
language: java
script:
  - jdk_switcher use oraclejdk8
  - mvn clean test jacoco:report package sonar:sonar 
jdk:
  - oraclejdk8
after_success:
  - mvn clean cobertura:cobertura coveralls:report
sudo: false
addons:
  sonarcloud:
    organization: "leonardxfce-github"
    token:
      secure: $SONAR_TOKEN
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
  
