language: java
sudo: false   # Linux OS: run in container
matrix:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
      env:
        - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - if [[ "${TRAVIS_OS_NAME}" == linux ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi
script:
  - mvn clean test jacoco:report package sonar:sonar 
after_success:
  - mvn clean cobertura:cobertura coveralls:report
sudo: false
addons:
  sonarcloud:
    organization: "leonardxfce-github"
    token:
      secure: $SONAR_TOKEN
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
 