os: osx
language: java
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
jdk:
  - oraclejdk8
sudo: false
addons:
  sonarcloud:
    organization: "leonardxfce-github"
    token:
      secure: $SONAR_TOKEN
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
  
